settings:
  title: 'Status Page'
  url: 'https://status-page.dillnguyen.workers.dev/' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: mmodaily.net # unique identifier
    name: mmodaily.net
    description: 'Website chạy thử dự án' # default=empty
    url: 'https://mmodaily.net/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true

  - id: norimomcare.com
    name: norimomcare.com
    description: 'Website của anh Hiro'
    url: 'https://norimomcare.com'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

  - id: dacsanvn.org
    name: 'Website của anh Hiro'
    url: 'https://dacsanvn.org/'
    method: GET
    expectStatus: 200
